<a href="https://colab.research.google.com/github/lakshh670/100_days_of_DeepLearning/blob/main/Embeddings_simple_RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# In this notebook we will se embeddings, a neural network technique which is used to vectorize the text. It is better the tokenizing and padding the text vectors because unlike padding it generates dense vectors and it also captures the sematic meaning(context) of the words.
# Initial steps are same, we need to tokenize and then do the padding of the text vectors

In [4]:
import numpy as np

docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [5]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer()

In [6]:
tokenizer.fit_on_texts(docs)

In [8]:
len(tokenizer.index_word)

17

In [15]:
sequences=tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [16]:
from keras.utils import pad_sequences
sequences=pad_sequences(sequences=sequences,padding='post')
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [18]:
from keras import Sequential
from keras.layers import Embedding, Dense,SimpleRNN,Flatten

In [26]:
model = Sequential()
model.add(Embedding(input_dim=18,output_dim=2,input_length=5))

model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [27]:
model.compile('adam','accuracy')

In [28]:
# Here we are not training the model. Just doing prediction on initial weights
pred=model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step
[[[ 0.00262059 -0.03676873]
  [ 0.02434867  0.00885778]
  [-0.01538421  0.01033012]
  [-0.01538421  0.01033012]
  [-0.01538421  0.01033012]]

 [[ 0.02434867  0.00885778]
  [ 0.02434867  0.00885778]
  [-0.01538421  0.01033012]
  [-0.01538421  0.01033012]
  [-0.01538421  0.01033012]]

 [[ 0.03382004 -0.01874331]
  [ 0.03382004 -0.01874331]
  [ 0.02709276  0.04952439]
  [-0.01538421  0.01033012]
  [-0.01538421  0.01033012]]

 [[-0.02964648  0.0457058 ]
  [ 0.04453272  0.03934688]
  [-0.02964648  0.0457058 ]
  [ 0.02434867  0.00885778]
  [-0.02964648  0.0457058 ]]

 [[ 0.03722924  0.00520612]
  [ 0.03628265 -0.00702041]
  [-0.01826273 -0.01578445]
  [-0.04104031  0.03644273]
  [-0.01538421  0.01033012]]

 [[ 0.04188215  0.0351685 ]
  [ 0.04188215  0.0351685 ]
  [-0.01538421  0.01033012]
  [-0.01538421  0.01033012]
  [-0.01538421  0.01033012]]

 [[ 0.03183224  0.04077505]
  [ 0.03183224  0.04077505]
  [-0.01538421  0.01033012]
  [-0.01538421  0.0103301

In [29]:
# Now lets build a simple RNN
from keras.datasets import imdb
(x_train,y_train),(x_test,y_test) = imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [30]:
x_train,x_test=pad_sequences(x_train,padding='post',maxlen=50),pad_sequences(x_test,padding='post',maxlen=50)

In [37]:
np.max(x_train)

np.int32(88585)

In [31]:
len(x_train)

25000

In [32]:
len(x_train[0])

50

In [40]:
model = Sequential()
model.add(Embedding(np.max(x_train)+1, 2,input_length=50))
model.add(SimpleRNN(32,return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_2 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [41]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(x_train, y_train,epochs=5,validation_data=(x_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 15s 16ms/step - acc: 0.5402 - loss: 0.6841 - val_acc: 0.7624 - val_loss: 0.5004
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 22s 18ms/step - acc: 0.8273 - loss: 0.3967 - val_acc: 0.8003 - val_loss: 0.4361
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 22s 20ms/step - acc: 0.9041 - loss: 0.2481 - val_acc: 0.8064 - val_loss: 0.4475
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - acc: 0.9422 - loss: 0.1656 - val_acc: 0.7832 - val_loss: 0.6433
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - acc: 0.9620 - loss: 0.1143 - val_acc: 0.7935 - val_loss: 0.5541
